### ISSUE TITLE
Where is the score function for Structure and coherence?

### ISSUE THREAD

**Issue by jmpu** [WanzhengZhu/GRUEN#1]
Hi, I think the current implementation only covers three sub-scores: get_grammaticality_score, get_redundancy_score, get_focus_score. Where is the fourth function for evaluating Structure and coherence? Could you please let me know if I miss anything?

**Comment by WanzhengZhu** [comment]
No, you did not miss anything. We have not yet include the fourth function for Structure and coherence for the current version. However, it should not affect using the metric score much since the metric still correlates with human judgments reasonably well even without the coherence measurement. 
We choose not to release it because 1) we are working on a better approach for evaluating structure and coherence now, and 2) the fourth function takes a large computational resources. The newer metric we are working on should be more convenient and efficient to use. We plan to release it later when ready.

**Comment by jmpu** [comment]
Thanks!
